# Generated by Django 3.1.3 on 2020-11-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essecommerceapp', '0003_customer_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
